apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.name }}
spec:
  schedule: {{ .Values.frequency | quote }}
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            iam.amazonaws.com/role: {{ .Values.iam.role }}
        spec:
          containers:
            - name: {{ .Values.name }} 
              imagePullPolicy: {{ .Values.image.imagePullPolicy }}
              image: {{ .Values.image.repo }}:{{ .Values.repo.tag }}
              args:
              - aws
              - "--snapshots-saved={{ .Values.snapshotsSaved }}"
              env:
                - name: AWS_REGION
                  value: {{ .Values.region }}
              volumeMounts:
              - name: ssl-certs
                mountPath: /etc/ssl/certs/ca-certificates.crt
                readOnly: true
          volumes:
            - name: ssl-certs
              hostPath:
                path: "/etc/ssl/certs/ca-certificates.crt"
          restartPolicy: OnFailure